#
# Travis CI configuration file
#

dist: trusty
language: csharp

cache:
  directories:
    - install

matrix:
  include:
    - os: osx
      osx_image: xcode9  # macOS 10.12
      dotnet: 2.0.0
      mono: latest
      env: MONO_BASE_PATH=/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/

addons:
  apt:
    packages:
      - dotnet-sharedframework-microsoft.netcore.app-1.0.5

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - UNITY_MAC_OS_PKG_PATH: install/UnityMacOS.pkg

install:
  - cp -R ngettext-unity tests/Assets/Editor/
  - >
    if [ ! -d install ]; then mkdir install; fi
  - >
    if [ ! -f $UNITY_MAC_OS_PKG_PATH ]; then curl -Lo $UNITY_MAC_OS_PKG_PATH https://netstorage.unity3d.com/unity/88d00a7498cd/MacEditorInstaller/Unity-5.5.1f1.pkg; fi
  - sudo installer -dumplog -package $UNITY_MAC_OS_PKG_PATH -target /

script:
  - >
    /Applications/Unity/Unity.app/Contents/MacOS/Unity -runTests 
      -testResults $(pwd)/results.xml
      -batchmode 
      -nographics 
      -logFile $(pwd)/unity.log 
      -projectPath $(pwd)/tests/
      -quit
